name: CI Dev

on:
  push:
#    branches: [ main ]
    branches: [ 'features/add-ci' ]

jobs:

    Build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Build image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: false
            tags: agora_frontend:latest

        - name: Save image to file
          run: |
            docker save -o agora_frontend.tar agora_frontend

        - name: Transfer image to VM
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.HOST_USERNAME }}
            password: ${{ secrets.HOST_PASSWORD }}
            port: "22"
            source: "agora_frontend.tar"
            target: "/home/agora/images"

    Deploy:
      needs: Build
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Load image from file
          uses: appleboy/ssh-action@v0.1.4
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.HOST_USERNAME }}
            password: ${{ secrets.HOST_PASSWORD }}
            script: |
              cd /home/agora/images
              sudo docker load -i agora_frontend.tar

        - name: Update docker service
          uses: appleboy/ssh-action@v0.1.4
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.HOST_USERNAME }}
            password: ${{ secrets.HOST_PASSWORD }}
            script: |
              sudo docker service update --image agora_frontend:latest agora_frontend --force

